FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Travel API

API Travel Service

## Authentication [/]

### Login [POST /login]
+ Request (application/json)

        {
            "username": "user",
            "password": "1234"
        }

    
+ Response 201 (application/json)

        {
            "token": "ghsogsgsodg",
            "data": {
                "username": "user",
                "profile": {
                    "address": "Ha nam",
                    "birthday": "1/2/2000",
                },
                "phone": "0964056932",
                "have_message": false,
                "notification": 2,
            }
        }
        
### Register [POST /register]
+ Request (application/json)

        {
            "username": "user",
            "password": "1234",
            "repassword": "1234",
            "phone": "0964056932",
            "address": "ha Nam",
            "birdthay": "",
        }

    
+ Response 201 (application/json)

        {
            "token": "ghsogsgsodg",
            "data": {
                "username": "user",
                "profile": {
                    "address": "Ha nam",
                    "birthday": "1/2/2000",
                },
                "phone": "0964056932",
                "have_message": false,
                "notification": 2,
            }
        }
        
### Login Token [POST /login/token]
+ Request (application/json)
    + Header
        Authentication : "Bear dfdghdg"
      
    
+ Response 201 (application/json)

        {
            "token": "ghsogsgsodg",
            "data": {
                "username": "user",
                "profile": {
                    "address": "Ha nam",
                    "birthday": "1/2/2000",
                },
                "phone": "0964056932",
                "have_message": false,
                "notification": 2,
            }
        }